# 是否启用路由，若关闭则默认直连
enable=true

#nfdy
[[routes]]
rules=[
"domain:netflix.com",
"domain:netflix.net",
"domain:netflixinvestor.com",
"domain:netflixtechblog.com",
"domain:nflxext.com",
"domain:nflximg.com",
"domain:nflximg.net",
"domain:nflxsearch.net",
"domain:nflxso.net",
"domain:nflxvideo.net",
"domain:disney.asia",
"domain:disney.be",
"domain:disney.bg",
"domain:disney.ca",
"domain:disney.ch",
"domain:disney.co.il",
"domain:disney.co.jp",
"domain:disney.co.kr",
"domain:disney.co.th",
"domain:disney.co.uk",
"domain:disney.co.za",
"domain:disney.com",
"domain:disney.com.au",
"domain:disney.com.br",
"domain:disney.com.hk",
"domain:disney.com.tw",
"domain:disney.cz",
"domain:disney.de",
"domain:disney.dk",
"domain:disney.es",
"domain:disney.fi",
"domain:disney.fr",
"domain:disney.gr",
"domain:disney.hu",
"domain:disney.id",
"domain:disney.in",
"domain:disney.io",
"domain:disney.it",
"domain:disney.my",
"domain:disney.nl",
"domain:disney.no",
"domain:disney.ph",
"domain:disney.pl",
"domain:disney.pt",
"domain:disney.ro",
"domain:disney.ru",
"domain:disney.se",
"domain:disney.sg",
"domain:20thcenturystudios.com.au",
"domain:20thcenturystudios.com.br",
"domain:20thcenturystudios.jp",
"domain:adventuresbydisney.com",
"domain:babble.com",
"domain:babyzone.com",
"domain:beautyandthebeastmusical.co.uk",
"domain:dilcdn.com",
"domain:disney-asia.com",
"domain:disney-discount.com",
"domain:disney-plus.net",
"domain:disney-studio.com",
"domain:disney-studio.net",
"domain:disneyadsales.com",
"domain:disneyarena.com",
"domain:disneyaulani.com",
"domain:disneybaby.com",
"domain:disneycareers.com",
"domain:disneychannelonstage.com",
"domain:disneychannelroadtrip.com",
"domain:disneycruisebrasil.com",
"domain:disneyenconcert.com",
"domain:disneyiejobs.com",
"domain:disneyinflight.com",
"domain:disneyinternational.com",
"domain:disneyinternationalhd.com",
"domain:disneyjunior.com",
"domain:disneyjuniortreataday.com",
"domain:disneylatino.com",
"domain:disneymagicmoments.co.il",
"domain:disneymagicmoments.co.uk",
"domain:disneymagicmoments.co.za",
"domain:disneymagicmoments.de",
"domain:disneymagicmoments.es",
"domain:disneymagicmoments.fr",
"domain:disneymagicmoments.gen.tr",
"domain:disneymagicmoments.gr",
"domain:disneymagicmoments.it",
"domain:disneymagicmoments.pl",
"domain:disneymagicmomentsme.com",
"domain:disneyme.com",
"domain:disneymeetingsandevents.com",
"domain:disneymovieinsiders.com",
"domain:disneymusicpromotion.com",
"domain:disneynewseries.com",
"domain:disneynow.com",
"domain:disneypeoplesurveys.com",
"domain:disneyplus.com",
"domain:disneyredirects.com",
"domain:disneysrivieraresort.com",
"domain:disneystore.com",
"domain:disneystreaming.com",
"domain:disneysubscription.com",
"domain:disneytickets.co.uk",
"domain:disneyturkiye.com.tr",
"domain:disneytvajobs.com",
"domain:disneyworld-go.com",
"domain:dssott.com",
"domain:go-disneyworldgo.com",
"domain:go.com",
"domain:mickey.tv",
"domain:moviesanywhere.com",
"domain:nomadlandmovie.ch",
"domain:playmation.com",
"domain:shopdisney.com",
"domain:shops-disney.com",
"domain:sorcerersarena.com",
"domain:spaindisney.com",
"domain:star-brasil.com",
"domain:star-latam.com",
"domain:starwars.com",
"domain:starwarsgalacticstarcruiser.com",
"domain:starwarskids.com",
"domain:streamingdisney.net",
"domain:thestationbymaker.com",
"domain:thisispolaris.com",
"domain:watchdisneyfe.com",
"domain:bamgrid.com",
"domain:disney.api.edge.bamgrid.com",
"domain:execute-api.us-east-1.amazonaws.com",
"domain:bam.nr-data.net",
"domain:bam-6.nr-data.net",
"domain:global.edge.bamgrid.com",
"domain:deploy.static.akamaitechnologies.com",
"domain:1e100.net",
"domain:r.cloudfront.net",
]

[[routes.Outs]]
listen="" 
type="ss"
server="aaa.com"
port=12345
password="asdasd"
cipher="aes-128-gcm"

#HKG
[[routes]]
rules=[
"domain:hbo.com",
"domain:hboasia.com",
"domain:hbogo.com",
"domain:hbogoasia.com",
"domain:hbogoasia.hk",
]

[[routes.Outs]]
listen=""
type="ss"
server="hkjs.nodefunction.vip"
port=1234
password="123456"
cipher="aes-256-gcm"

#JPN
[[routes]]
rules=[
"domain:abema.io",
"domain:abema.tv",
"domain:ds-linear-abematv.akamaized.net",
"domain:linear-abematv.akamaized.net",
"domain:ds-vod-abematv.akamaized.net",
"domain:vod-abematv.akamaized.net",
"domain:ameba.jp",
"domain:hayabusa.io",
"domain:mobile-collector.newrelic.com",
"domain:vod-abematv.akamaized.net",
"domain:bucketeer.jp",
"domain:abema.adx.promo",
"domain:hayabusa.media",
"domain:control.kochava.com",
"domain:d151l6v8er5bdm.cloudfront.net",
"domain:d1sgwhnao7452x.cloudfront.net",
"domain:dazn-api.com",
"domain:dazn.com",
"domain:dazndn.com",
"domain:dc2-vodhls-perform.secure.footprint.net",
"domain:dca-ll-livedazn-dznlivejp.s.llnwi.net",
"domain:dcalivedazn.akamaized.net",
"domain:dcblivedazn.akamaized.net",
"domain:indazn.com",
"domain:indaznlab.com",
"domain:intercom.io",
"domain:logx.optimizely.com",
"domain:s.yimg.jp",
"domain:sentry.io",
"domain:dmc.nico",
"domain:nicovideo.jp",
"domain:nimg.jp",
"domain:socdm.com",
"domain:cygames.jp",
"domain:konosubafd.jp",
"domain:colorfulpalette.org",
"domain:cds1.clubdam.com",
"domain:api.worldflipper.jp",
]

[[routes.Outs]]
listen=""
type="ss"
server="jpjs.nodefunction.vip"
port=1234
password="123456"
cipher="aes-256-gcm"

#TWN
[[routes]]
rules=[
"domain:gamer.com.tw",
"domain:bahamut.com.tw",
"domain:hinet.net",
"domain:fbcdn.net",
"domain:gvt1.com",
"domain:digicert.com",
"domain:viblast.com",
"domain:akamaized.net",
"domain:acg.tv",
"domain:acgvideo.com",
"domain:b23.tv",
"domain:bigfun.cn",
"domain:biliapi.com",
"domain:biliapi.net",
"domain:bilibili.com",
"domain:bilibili.tv",
"domain:bilibiligame.net",
"domain:bilicdn1.com",
"domain:bilicdn2.com",
"domain:bilicdn3.com",
"domain:bilicdn4.com",
"domain:bilicdn5.com",
"domain:biligame.com",
"domain:biligame.net",
"domain:bilivideo.com",
"domain:bilivideo.cn",
"domain:hdslb.com",
"domain:im9.com",
"domain:mincdn.com",
"domain:biligo.com",
]

[[routes.Outs]]
listen=""
type="ss"
server="twjs.nodefunction.vip"
port=1234
password="123456"
cipher="aes-256-gcm"

#USA
[[routes]]
rules=[
"domain:max.com",
"geosite:tiktok",
]

[[routes.Outs]]
listen=""
type="ss"
server="usjs.nodefunction.vip"
port=1234
password="123456"
cipher="aes-256-gcm"

#SGP
[[routes]]
rules=[
"domain:byspotify.com",
"domain:pscdn.co",
"domain:scdn.co",
"domain:spoti.fi",
"domain:spotify-everywhere.com",
"domain:spotify.com",
"domain:spotify.design",
"domain:spotifycdn.com",
"domain:spotifycdn.net",
"domain:spotifycharts.com",
"domain:spotifycodes.com",
"domain:spotifyforbrands.com",
"domain:spotifyjobs.com",
"domain:platform.openai.com", 
"domain:beta.openai.com",
"domain:auth0.openai.com",
"domain:auth1.openai.com",
"domain:auth2.openai.com",
"domain:openai.com",
"domain:chat.openai.com",
]

[[routes.Outs]]
listen=""
type="ss"
server="sgjs.nodefunction.vip"
port=1234
password="123456"
cipher="aes-256-gcm"

# 路由 N，最后一个路由兜底，否则无法匹配剩余的域名/IP
[[routes]]
# "*" 表示匹配任何域名/IP
rules=["*"]

# 配置直连出口
[[routes.Outs]]
listen="" 
type="direct"
